---
title: "BeachWatch Model"
format: html
editor_options: 
  chunk_output_type: console
---

This notebook reads in the BeachWatch data and fits a model to predict water
temperature at Sydney beaches. 

## Setup 

```{r}
library(tidyverse)
library(mgcv)
```

## Get Data  

From: https://beachwatch.nsw.gov.au/waterMonitoring/waterQualityData

```{r}
water_raw <- read_csv("data/Water quality-1727670437021.csv")
```

## Clean Data  

```{r}
water <- water_raw |> 
  transmute(temp = `Water temperature (°C)`,
         beach = `Swim site`,
         date = Date,
         time = Time) |> 
  mutate(date = dmy(date),
         month = month(date),
         hour = hour(time),
         month_lab = month(date, label = TRUE),
         beach = as.factor(beach)) 

```

## EDA  

```{r}
water |> 
  count(beach, sort = TRUE)
```

```{r}
ggplot(data = water) +
  geom_boxplot(aes(month_lab, temp))
```

Anomalies present, removing anything > 40 degrees C  

```{r}
water_clean <- water |> 
  filter(temp < 40) 
```

```{r}
water_clean |> 
  ggplot() +
  geom_boxplot(aes(month_lab, temp))
```

```{r}
water_clean |> 
  ggplot() +
  geom_histogram(aes(temp), binwidth = 1)
```

```{r}
water_clean |> 
  count(month, hour) |> 
  ggplot() +
  geom_tile(aes(hour, month, fill = n))
```

## Model 

Fitting a GAM to predict Water Temperature.  

```{r}
library(mgcv)

mod_gam <- mgcv::gam(temp ~ s(month, bs = "cc", k = 12) + s(hour) + s(beach, bs = "re"), data = water_clean)

mod_gam

summary(mod_gam)
plot(mod_gam)
```

Prediction

```{r}
predict(mod_gam, newdata = data.frame(month = 12, hour = 8, beach = "Bondi Beach"))
```

Save Model

```{r}
saveRDS(mod_gam, "deploy/beachwatch_model.rds")
```

