# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/home/deanmarchiori/workspace/beachwatch/inst/deploy")
v <- vetiver_pin_read(b, "sydney-beach-gam", version = "20241007T021501Z-bb3f3")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
